services:
  db:
    image: postgres:16
    container_name: boardgame_postgres
    environment:
      POSTGRES_DB: boardgame_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dream0137
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  web:
    build: .
    container_name: boardgame_web
    environment:
      POSTGRES_DB: boardgame_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dream0137
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    ports:
      - "8001:8000"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  pgdata: